#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm's
export _JAVA_AWT_WM_NONREPARENTING=1

MONITOR_NAME="HDMI-0"

bspc monitor $MONITOR_NAME -d 1 2 3 4 5 6

bspc config border_width        	4
bspc config window_gap           	20
bspc config top_padding          	45
bspc config bottom_padding       	2

bspc config split_ratio         	0.5
bspc config single_monocle		false
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus     	false
bspc config borderless_monocle		true
bspc config gapless_monocle     	true

bspc config focused_border_color     "#3b4261"
bspc config normal_border_color      "#1f2335"

bspc rule -a dialog state=floating follow=on
bspc rule -a Dialog state=floating follow=on
bspc rule -a confirmreset state=floating follow=on
bspc rule -a branchdialog state=floating follow=on

# Adding a screensaver sflock
# xss-lock --transfer-sleep-lock -- sflock &

# Autostart

bash /home/$(whoami)/.config/dotfiles/config/scripts/autorun.sh

xsetroot -cursor_name left_ptr &
